server:
  port: 28025
dubbo:
  protocol:
    port: ${DUBBO_PROTOCOL_PORT:28825}
  service:
    version: 1.0.0

spring:
  application:
    name: dubbo-provider

feign:
  hystrix:
    enabled: true

management:
  endpoint:
    health:
      probes:
        enabled: true